name: Build

on:
  push:
    branches:
      - main

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libtool pkg-config \
                                  openjdk-11-jdk zlib1g-dev

      - name: Install distutils
        run: |
          pip install setuptools

      - name: Install cython
        run: |
          pip install cython

      - name: Install Buildozer and other dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: .
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: output-apk
          path: bin/*.apk  # Adjust the path if necessary
